version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: socket.io
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
    - 2.0.0
    - 2.0.1
  - dependency-name: react-dom
    versions:
    - 16.14.0
    - 17.0.1
  - dependency-name: validator
    versions:
    - 13.5.2
  - dependency-name: inquirer
    versions:
    - 7.3.3
  - dependency-name: gulp-babel
    versions:
    - 7.0.1
